name: 'Kingly Frontend'
type: 'Site'
description: 'Configures Kingly frontend.'

install:
  - kingly_theme

config:
  strict: false
  actions:
    system.theme:
      simpleConfigUpdate:
        default: kingly_theme
