name: 'Kingly Frontend'
type: 'Site'
description: 'Configures Kingly frontend.'

install:
  - menu_link_content
  - kingly_theme

config:
  strict: false
  actions:
    # Disable blocks.
    block.block.kingly_theme_search_form:
      simple_config_update:
        status: false
    block.block.kingly_theme_tools:
      simple_config_update:
        status: false
    block.block.kingly_theme_admin:
      simple_config_update:
        status: false
    node.settings:
      simple_config_update:
        use_admin_theme: true
    user.settings:
      simple_config_update:
        register: admin_only
    system.theme:
      simple_config_update:
        default: kingly_theme
