name: 'Kingly Frontend'
type: 'Site'
description: 'Configures Kingly frontend.'

install:
  - solo

config:
  strict: false
  import:
    solo:
      - solo.settings
      - block.block.solo_branding
      - block.block.solo_breadcrumbs
      - block.block.solo_content
      - block.block.solo_footer
      - block.block.solo_local_actions
      - block.block.solo_local_tasks
      - block.block.solo_main_menu
      - block.block.solo_messages
      - block.block.solo_page_title
      - block.block.solo_userlogin
  actions:
    block.block.solo_userlogin:
      simple_config_update:
        region: popup_login_block
    block.block.solo_branding:
      simple_config_update:
        region: header
        weight: -10
    block.block.solo_main_menu:
      simple_config_update:
        region: primary_menu
    block.block.solo_messages:
      simple_config_update:
        region: system_messages
    block.block.solo_page_title:
      simple_config_update:
        region: page_title
    block.block.solo_breadcrumbs:
      simple_config_update:
        region: breadcrumb
    block.block.solo_local_tasks:
      simple_config_update:
        region: content
    block.block.solo_local_actions:
      simple_config_update:
        region: content
    block.block.solo_content:
      simple_config_update:
        region: content
    block.block.solo_footer:
      simple_config_update:
        region: footer_menu
    block.block.solo_search_form:
      simple_config_update:
        region: fixed_search_block
    block.block.solo_search_form_primary:
      simple_config_update:
        region: fixed_search_block
        status: false
    # Disable blocks.
    block.block.solo_tools:
      simple_config_update:
        status: false
    block.block.solo_admin:
      simple_config_update:
        status: false
    system.theme:
      simpleConfigUpdate:
        default: solo
