name: 'Kingly Frontend'
type: 'Site'
description: 'Configures Kingly frontend.'

install:
  - solo

config:
  strict: false
  import:
    solo: '*'
  actions:
#    block.block.solo_powered:
#      setStatus: false
    system.theme:
      simpleConfigUpdate:
        default: solo
#    system.site:
#      simpleConfigUpdate:
#        page.front: /node/1
