name: 'Kingly Frontend'
type: 'Site'
description: 'Configures Kingly frontend.'

install:
  - menu_link_content
  - kingly_theme

config:
  strict: false
  actions:
    block.block.kingly_theme_main_navigation:
      simple_config_update:
        region: primary_menu
        weight: -10
    block.block.kingly_theme_search_form:
      simple_config_update:
        region: header
        status: false
    block.block.kingly_theme_search_form_primary:
      simple_config_update:
        region: header
        status: false
    block.block.kingly_theme_messages:
      simple_config_update:
        region: content
    block.block.kingly_theme_page_title:
      simple_config_update:
        region: content
    block.block.kingly_theme_local_tasks:
      simple_config_update:
        region: content
    block.block.kingly_theme_local_actions:
      simple_config_update:
        region: content
    # Disable blocks.
    block.block.kingly_theme_tools:
      simple_config_update:
        status: false
    block.block.kingly_theme_admin:
      simple_config_update:
        status: false
    node.settings:
      simple_config_update:
        use_admin_theme: true
    user.settings:
      simple_config_update:
        register: admin_only
    system.theme:
      simple_config_update:
        default: kingly_theme
